language: ruby
rvm:
    - 2.2.2
env:
    - DB=postgresql
services:
    - postgresql
before_install:
    - cd webapp
script:
    - RAILS_ENV=test bundle exec rake db:migrate --trace
    - bundle exec rake db:test:prepare
    - bundle exec rake db:fixtures:load
    - bundle exec rails server &
    - bundle exec rake
before_script:
    - psql -c 'create database simpleref_test;' -U postgres
    - psql -c 'create database test;' -U postgres
