---
- hosts: db

  tasks:
    - name: Update apt repositories
      apt:
        update-cache: yes

    - name: Upgrade installed packages
      apt:
        upgrade: yes

    - name: Install Git
      apt: pkg=git state=installed

    - name: Install Postgres
      apt: pkg=postgresql state=installed

    - name: Add Github.com to machine-wide known_hosts
      become: yes
      become_user: root
      known_hosts:
        path: '/etc/ssh/ssh_known_hosts'
        name: 'github.com'
        key: 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='

    - name: Create user admin
      user: name=admin group=admin

    - name: Add Git private key to user admin
      copy:
        src: "sec/git-repo-priv-key.txt"
        dest: /home/admin/.ssh/id_rsa
        mode: 0600
        owner: admin
        group: admin

    - name: Clone git repository
      become: yes
      become_user: admin
      git:
        repo: git@github.com:xnbya/TeamDisrupt.git
        dest: ~/TeamDisrupt
        version: scripting
