# -*- mode: ruby -*-
# vi: set ft=ruby :

hosts = {
  "production" => "192.168.33.10",
  "staging" => "192.168.33.100",
  "db" => "192.168.33.200"
}

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  #config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true

  hosts.each do |name, ip|
    config.vm.define name do |machine|
      machine.vm.hostname = "%s.local" % name
      #machine.ssh.host = ip
      machine.vm.network "private_network", ip: ip
    end
  end
end
