---
- name: Create ec2 instance
  hosts: 127.0.0.1
  connection: local
  become: no
  gather_facts: False

  tasks:
    - name: Launch instance
      action:
        module: ec2
        key_name: george-aws
        # Ubuntu 16.04 LTS
        image: ami-8504fdea
        instance_type: t2.micro
        instance_tags:
          Name: "{{ name }}"
        region: eu-central-1
        zone: eu-central-1a
        vpc_subnet_id: subnet-c606b3ae
        # Note this is security group NAME, not id
        group: allow-all
        state: present
        user_data: |
          #!/bin/bash
          apt-get update
          apt-get install -y python-simplejson
      register: ec2

    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=launched
      with_items: '{{ec2.instances}}'

    - name: "Wait for the instance to boot and start ssh"
      wait_for:
        host: "{{item.public_ip}}"
        port: 22
        delay: 5
        timeout: 300
      with_items: "{{ ec2.tagged_instances }}"
      when: ec2|changed

    - name: "Wait for cloud init on first boot"
      pause: minutes=2
      when: ec2|changed
